[package]
name = "dnd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
approx = "0.5.1"
derive_more = { version = "2.0.1", features = ["display"] }
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
tuirealm = "2.0.3"
